=== zchalmers/CSE445-Assignment4/NationalParks.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
  xmlns="http://zchalmers.github.io/CSE445-Assignment4"
  targetNamespace="http://zchalmers.github.io/CSE445-Assignment4"
  elementFormDefault="qualified"
  attributeFormDefault="unqualified">

  <xs:element name="NationalParks">
    <xs:annotation>
      <xs:documentation>CSE445 Assignment 4 National Parks.</xs:documentation>
    </xs:annotation>
    <xs:complexType>
      <xs:sequence>
        <xs:element name="NationalPark" maxOccurs="unbounded">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="Name" type="xs:string"/>
              <xs:element name="Phone" type="xs:string" minOccurs="1" maxOccurs="unbounded"/>
              <xs:element name="Address">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="Number" type="xs:string"/>
                    <xs:element name="Street" type="xs:string"/>
                    <xs:element name="City" type="xs:string"/>
                    <xs:element name="State" type="xs:string"/>
                    <xs:element name="Zip" type="xs:string"/>
                  </xs:sequence>
                  <xs:attribute name="NearestAirport" type="xs:string" use="optional"/>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
            <xs:attribute name="Region" type="xs:string" use="required"/>
            <xs:attribute name="Rating" type="xs:string" use="optional"/>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>

</xs:schema>

=== zchalmers/CSE445-Assignment4/NationalParks.xml
<?xml version="1.0" encoding="UTF-8"?>
<NationalParks xmlns="http://zchalmers.github.io/CSE445-Assignment4"
               xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
               xsi:schemaLocation="http://zchalmers.github.io/CSE445-Assignment4 NationalParks.xsd">

  <NationalPark Region="Southwest" Rating="4.9">
    <Name>Grand Canyon</Name>
    <Phone>123-123-1234</Phone>
    <Phone>123-123-1234</Phone>
    <Phone>123-123-1234</Phone>
    <Address NearestAirport="FlagStaff">
      <Number>8</Number>
      <Street>S Entrance Road</Street>
      <City>Grand Canyon</City>
      <State>AZ</State>
      <Zip>86023</Zip>
    </Address>
  </NationalPark>

  <NationalPark Region="Rockies">
    <Name>Yellowstone</Name>
    <Phone>123-123-1234</Phone>
    <Phone>123-123-1234</Phone>
    <Address>
      <Number>2</Number>
      <Street>Yellowstone Park Road</Street>
      <City>Yellowstone National Park</City>
      <State>WY</State>
      <Zip>82190</Zip>
    </Address>
  </NationalPark>

  <NationalPark Region="West" Rating="4.9">
    <Name>Yosemite</Name>
    <Phone>123-123-1234</Phone>
    <Address NearestAirport="Fresno">
      <Number>9035</Number>
      <Street>Village Drive</Street>
      <City>Yosemite Valley</City>
      <State>CA</State>
      <Zip>95389</Zip>
    </Address>
  </NationalPark>

  <NationalPark Region="Southwest">
    <Name>Zion</Name>
    <Phone>123-123-1234</Phone>
    <Phone>123-123-1234</Phone>
    <Address NearestAirport="St.George">
      <Number>1</Number>
      <Street>Zion Canyon Scenic Drive</Street>
      <City>Springdale</City>
      <State>UT</State>
      <Zip>84767</Zip>
    </Address>
  </NationalPark>

  <NationalPark Region="Rockies" Rating="4.8">
    <Name>Rocky Mountain</Name>
    <Phone>123-123-1234</Phone>
    <Address>
      <Number>1000</Number>
      <Street>US-36</Street>
      <City>Estes Park</City>
      <State>CO</State>
      <Zip>80517</Zip>
    </Address>
  </NationalPark>

  <NationalPark Region="Northeast">
    <Name>Acadia</Name>
    <Phone>123-123-1234</Phone>
    <Phone>123-123-1234</Phone>
    <Address NearestAirport="Bangor">
      <Number>20</Number>
      <Street>McFarland Hill Drive</Street>
      <City>Bar Harbor</City>
      <State>ME</State>
      <Zip>04609</Zip>
    </Address>
  </NationalPark>

  <NationalPark Region="Southeast" Rating="4.9">
    <Name>Great Smoky Mountains</Name>
    <Phone>123-123-1234</Phone>
    <Address>
      <Number>107</Number>
      <Street>Park Headquarters Road</Street>
      <City>Gatlinburg</City>
      <State>TN</State>
      <Zip>37738</Zip>
    </Address>
  </NationalPark>

  <NationalPark Region="Southwest">
    <Name>Bryce Canyon</Name>
    <Phone>123-123-1234</Phone>
    <Address>
      <Number>1</Number>
      <Street>Bryce Canyon Scenic Drive</Street>
      <City>Bryce Canyon City</City>
      <State>UT</State>
      <Zip>84717</Zip>
    </Address>
  </NationalPark>

  <NationalPark Region="Southwest" Rating="4.7">
    <Name>Arches</Name>
    <Phone>123-123-1234</Phone>
    <Phone>123-123-1234</Phone>
    <Address NearestAirport="Grand Junction">
      <Number>1</Number>
      <Street>Manhattan Viewpoint</Street>
      <City>Moab</City>
      <State>UT</State>
      <Zip>84532</Zip>
    </Address>
  </NationalPark>

  <NationalPark Region="Pacific Northwest">
    <Name>Olympic</Name>
    <Phone>123-123-1234</Phone>
    <Address>
      <Number>3002</Number>
      <Street>Angeles Road</Street>
      <City>Port Angeles</City>
      <State>WA</State>
      <Zip>98362</Zip>
    </Address>
  </NationalPark>

  <NationalPark Region="West" Rating="4.8">
    <Name>Joshua Tree</Name>
    <Phone>123-123-1234</Phone>
    <Phone>123-123-1234</Phone>
    <Address>
      <Number>74485</Number>
      <Street>National Park Drive</Street>
      <City>Twentynine Palms</City>
      <State>CA</State>
      <Zip>92277</Zip>
    </Address>
  </NationalPark>

  <NationalPark Region="Alaska">
    <Name>Denali</Name>
    <Phone>123-123-1234</Phone>
    <Address NearestAirport="Fairbanks">
      <Number>1</Number>
      <Street>Park Road</Street>
      <City>Denali Park</City>
      <State>AK</State>
      <Zip>99755</Zip>
    </Address>
  </NationalPark>
</NationalParks>
